### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlite3_to_mysql'

### ISSUE THREAD

**Issue by marcpre** [ArefDev/Berudele#4]
Hello,

I am using `Ubuntu 18` and I am using `Python 3.6.9`

```
$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from res.logic.transfer import run_transfer
  File "/home/marcus/Desktop/Del_Me/Berudele/res/logic/transfer.py", line 5, in <module>
    import sqlite3_to_mysql
ModuleNotFoundError: No module named 'sqlite3_to_mysql'
```

Any suggestions why the module is not found?

I appreciate your replies!

**Comment by lemones** [comment]
Did you install sqlite3-to-mysql?
`$ pip install sqlite3-to-mysql`
